config/routes.rb
Rails.application.routes.draw do
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'login', to: 'sessions#new', as: 'login'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users
  resources :products
  match('/products_uploads', {:via => :post, :to => "product_uploads#create"})
  #resources :product_uploads

  root to: "users#index"
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/product_upload.rb
class ProductUpload
  extend ActiveModel::Model
  # include ActiveModel::Conversion
  # def persisted?
  #   false
  # end

  def initialize(file)
    @file = file
  end

  def parse!
    products_attributes = SmarterCSV.process(@file)
    products_attributes.each do |product_attributes|
      Product.create(product_attributes)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => true


  def make_admin
    self.update(:admin => true)
  end

  def remove_admin
    self.update(:admin => false)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end

  def authorize
    redirect_to '/users/', alert: "You need to be an admin." if !current_user || !current_user.admin
  end

  helper_method :current_user
end

app/controllers/product_uploads_controller.rb
class ProductUploadsController < ApplicationController

  def create
    if ProductUpload.new(params[:product_upload][:csv]).parse!
      redirect_to('/products')
    else
      redirect_to('/products/new')
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    #@product_upload = ProductUpload.new
  end

  def index
    @products = Product.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/', notice: "Welcome"
    else
      flash[:alert] = "Email or is invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/', notice: "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize, except: [:index]

  def index
    @users = User.all
    render 'index'
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.remove_admin
      index
    else
      flash[:alert] = "User not added."
      redirect_to '/users/new'
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HorrorsOn13th</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-3 navigation">
        <% if current_user %>
          <p>Logged in as <%= current_user.name %></p>
          <%= link_to 'Logout', logout_path %>
        <% else %>
          <%= link_to 'Login', login_path %>
        <% end %>
        <%= yield(:navigation) %>
      </div>
      <div class="col-md-9 header">
        <%= yield(:header) %>
        <%= flash[:notice] %>
        <%= flash[:alert] %>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/products/index.html.erb
<ul>
  <% @products.each do |product| %>
    <li><%= product.name %></li>
  <% end %>
</ul>

app/views/products/new.html.erb
<%= content_for(:navigation) do %>
<% end %>

<%= content_for(:header) do %>
  <h1>Upload new products</h1>
<% end %>

<%= form_tag "/products_uploads/" do %>
  <label for="csv">CSV to Upload</label>
  <%= file_field_tag "product_upload[csv]" %>
  <%= submit_tag %>
<% end %>

app/views/users/index.html.erb
<% if current_user %>


  <%= content_for(:navigation) do %>
    <% if current_user.admin %>
      <p><%= link_to 'Add New User', new_user_path %></p>
    <% end %>
    <p><%= link_to 'Add New Product', new_product_path %></p>
  <% end %>

  <%= content_for(:header) do %>
    <h1>All Users</h1>
  <% end %>

  <ul>
    <% @users.each do |user| %>
      <li><%= link_to "#{user.name}", user_path(user) %></li>
    <% end %>
  </ul>

<% end %>

app/views/users/new.html.erb
<%= content_for(:navigation) do %>
<% end %>

<%= content_for(:header) do %>
  <h1>Add new user</h1>
<% end %>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= submit_tag "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>